import inputs from '@/data/inputs.json'

/**
 * The input files that ship with the site, and the two questions a server
 * component needs to ask about them.
 *
 * These live here rather than next to the component that draws them because a
 * `'use client'` module exports components across the boundary, not functions:
 * calling one from a server component throws at request time, and nothing in a
 * type check or a build catches it. A plain module is importable from both
 * sides, which is what these need to be.
 *
 * Generated by `npm run inputs` from `code/evals/fixtures`.
 */

export const INPUTS = inputs.files

export type InputName = keyof typeof INPUTS

/** Whether a filename out of a receipt is one of the files shipped with the site. */
export function isAttached (name: string): name is InputName {
  return Object.hasOwn(INPUTS, name)
}

/** The last segment of a path the engine wrote, Windows separators included. */
export function baseName (path: string) {
  return path.split(/[\\/]/).pop() ?? path
}

/** Bytes, in the unit a person would say out loud. */
export function fileSize (bytes: number) {
  return bytes < 1024 ? `${bytes} B` : `${(bytes / 1024).toFixed(1)} KB`
}
